I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 149, in script
    show Neit_main_2 left
Exception: Image 'Neit_main_2' does not accept attributes 'left'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 149, in script
    show Neit_main_2 left
  File "C:\Program Files\renpy-8.3.2-sdk\renpy\ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Program Files\renpy-8.3.2-sdk\renpy\ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "C:\Program Files\renpy-8.3.2-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Program Files\renpy-8.3.2-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Program Files\renpy-8.3.2-sdk\renpy\display\transform.py", line 1188, in _duplicate
    args.extraneous()
  File "C:\Program Files\renpy-8.3.2-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'Neit_main_2' does not accept attributes 'left'.

Windows-10-10.0.22635 AMD64
Ren'Py 8.3.2.24090902
programmer1c Beta 0.0.0.0.1
Sun Dec 22 20:13:41 2024
